/**
 * City registry — the frontend half of data/cities.py.
 *
 * `cityRegistry.json` is generated by `python3 data/cities.py` and committed;
 * INV-024 fails if it drifts from the Python source. Nothing here re-states
 * facts about a city — centre, zoom, lines, colors, station count and
 * capabilities all come from that file, so adding a city is a registry edit
 * plus a processor, never a frontend edit.
 */
import REGISTRY from './cityRegistry.json'

export const CITIES = REGISTRY.cities
export const DEFAULT_CITY_SLUG = REGISTRY.defaultCity

const BY_SLUG = new Map(CITIES.map(c => [c.slug, c]))

export const CITY_SLUGS = CITIES.map(c => c.slug)

/** Capability names a city's dataset can declare (mirrors data/cities.py). */
export const CAP_WALKSHEDS = 'walksheds'
export const CAP_POIS = 'pois'
export const CAP_EXITS = 'exits'

export function isCitySlug(slug) {
  return BY_SLUG.has(slug)
}

/** Look up a city by slug, falling back to the default for unknown input. */
export function cityBySlug(slug) {
  return BY_SLUG.get(slug) || BY_SLUG.get(DEFAULT_CITY_SLUG)
}

export function hasCapability(city, capability) {
  return Boolean(city?.capabilities?.includes(capability))
}

/**
 * Public base URL for one of a city's data files.
 *
 * Every per-city artifact lives under `public/cities/<slug>/`, so the runtime
 * only ever needs the city and a relative name — there are no city-specific
 * paths spread through the fetch call sites.
 */
export function cityAsset(city, path) {
  return `${import.meta.env.BASE_URL}cities/${city.slug}/${path}`
}

/** The line whose `key` appears in a station's `lines` property. */
export function lineByKey(city, key) {
  return city.lines.find(l => l.key === key) || null
}

export function lineById(city, id) {
  return city.lines.find(l => l.id === id) || null
}

/** `{ '1-line': { color, label }, ... }` — the shape the legend and pills want. */
export function lineColors(city, darkMode = false) {
  const out = {}
  for (const line of city.lines) {
    out[line.id] = {
      color: darkMode ? line.colorDark : line.color,
      label: line.label,
      glyph: line.glyph,
      key: line.key,
    }
  }
  return out
}

export function walkshedAccent(city, darkMode = false) {
  return darkMode ? city.walkshedAccent.dark : city.walkshedAccent.light
}

/** Every `lines` value a station in this city may carry, e.g. '1', '2', '1,2'. */
export function validLineValues(city) {
  const keys = city.lines.map(l => l.key)
  const out = new Set()
  for (let i = 0; i < keys.length; i++) {
    for (let j = i + 1; j <= keys.length; j++) out.add(keys.slice(i, j).join(','))
  }
  return out
}

const STORAGE_KEY = 'walksheds_city'

/**
 * Resolve which city to show: an explicit `?city=` wins (so shared links are
 * stable), then the last city this browser chose, then the default.
 *
 * `search` and `storage` are injectable so the embed path can opt out of
 * persistence entirely (the iframe shares the real site's origin storage).
 */
export function resolveCity({ search = '', storage = null } = {}) {
  const fromUrl = new URLSearchParams(search).get('city')
  if (fromUrl && isCitySlug(fromUrl)) return cityBySlug(fromUrl)

  if (storage) {
    try {
      const stored = storage.getItem(STORAGE_KEY)
      if (stored && isCitySlug(stored)) return cityBySlug(stored)
    } catch { /* private mode */ }
  }
  return cityBySlug(DEFAULT_CITY_SLUG)
}

export function rememberCity(slug, storage) {
  if (!storage || !isCitySlug(slug)) return
  try { storage.setItem(STORAGE_KEY, slug) } catch { /* private mode */ }
}

export { STORAGE_KEY as CITY_STORAGE_KEY }
