import { cityAsset } from './cities'

/**
 * Load pre-generated station pill icons from a city's sprite sheet.
 * Icons are generated by data/process.py into public/cities/<slug>/icons/.
 *
 * Loads one JSON manifest + one PNG sprite sheet, then slices each
 * icon out via canvas — much faster than generating one SVG per station
 * at runtime.
 */
export async function registerStationIcons(map, city) {
  const dpr = window.devicePixelRatio >= 2 ? '@2x' : ''

  const [manifest, sheetImg] = await Promise.all([
    fetch(cityAsset(city, `icons/stations${dpr}.json`)).then(r => r.json()),
    new Promise((resolve, reject) => {
      const img = new Image()
      img.onload = () => resolve(img)
      img.onerror = reject
      img.src = cityAsset(city, `icons/stations${dpr}.png`)
    }),
  ])

  const canvas = document.createElement('canvas')
  const ctx = canvas.getContext('2d')

  for (const [key, spec] of Object.entries(manifest)) {
    if (map.hasImage(key)) continue
    const pw = spec.width * spec.pixelRatio
    const ph = spec.height * spec.pixelRatio
    canvas.width = pw
    canvas.height = ph
    ctx.clearRect(0, 0, pw, ph)
    ctx.drawImage(sheetImg, spec.x, spec.y, pw, ph, 0, 0, pw, ph)
    const imageData = ctx.getImageData(0, 0, pw, ph)
    map.addImage(key, { data: imageData.data, width: pw, height: ph }, { pixelRatio: spec.pixelRatio })
  }
}
